export const admins = [
  {
    id: "1",
    name: "Ekaterina Tankova",
    email: "xxxxx@gmail.com",
    avatar: "/static/images/avatars/avatar_2.png",
    phone: "304-428-3097",
    address: {
      country: "USA",
      state: "West Virginia",
      city: "Parkersburg",
      street: "2849 Fulton Street",
    },
    createdAt: 1555016400000,
  },
  {
    id: "2",
    name: "Cao Yu",
    email: "xxxxx@gmail.com",
    avatar: "/static/images/avatars/avatar_3.png",
    phone: "712-351-5711",
    address: {
      country: "USA",
      state: "Bristow",
      city: "Iowa",
      street: "1865  Pleasant Hill Road",
    },
    createdAt: 1555016400000,
  },
  {
    id: "3",
    name: "Alexa Richardson",
    email: "",
    avatar: "/static/images/avatars/avatar_4.png",
    phone: "770-635-2682",
    address: {
      country: "USA",
      state: "Georgia",
      city: "Atlanta",
      street: "4894  Lakeland Park Drive",
    },
    createdAt: 1555016400000,
  },
  {
    id: "4",
    name: "Anje Keizer",
    email: "",
    avatar: "/static/images/avatars/avatar_5.png",
    phone: "908-691-3242",
    address: {
      country: "USA",
      state: "New Jersey",
      city: "Bernardsville",
      street: "621  Camden Street",
    },
    createdAt: 1554930000000,
  },
  {
    id: "5",
    name: "Clarke Gillebert",
    email: "",
    avatar: "/static/images/avatars/avatar_6.png",
    phone: "972-333-4106",
    address: {
      country: "USA",
      state: "Texas",
      city: "Dallas",
      street: "75247",
    },
    createdAt: 1554757200000,
  },
  {
    id: "6",
    name: "Adam Denisov",
    email: "",
    avatar: "/static/images/avatars/avatar_7.png",
    phone: "858-602-3409",
    address: {
      country: "USA",
      state: "California",
      city: "San Francisco",
      street: "San Francisco",
    },
    createdAt: 1554670800000,
  },
];
