import SideNav from "../components/side-nav";
import "./globals.css";
import { Inter } from "next/font/google";
import RootProvider from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootProvider>
          <div>
            <SideNav />
            <div className="ml-[280px]">{children}</div>
          </div>
        </RootProvider>
      </body>
    </html>
  );
}
